id: local
enabled: true
display: <gold>Local
format: "<color:#DAA520>[Local]</color> <white>{name} ➻ {message}</white>"
radius: 50

commands:
  - local
  - l
  - lc

requirements:
  - "PERMISSION:chatchannel.local"

ping:
  enable: true
  cooldown: 10
  sound:
    sound: entity.experience_orb.pickup
    volume: 3
    pitch: 1