# Controls whether this channel is enabled.
enabled: true

# How should this channel be displayed in placeholders and messages?
display: <gold>Local

# How should messages in this channel be formatted?
format: "<color:#DAA520>[Local]</color> <white>{name} ➻ {message}</white>"

# Which commands should be used as a shortcut to enter this channel?
# This requires a server restart to take effect.
commands:
  - local
  - l
  - lc

# The requirements to access the channel.
requirements:
  - "PERMISSION:chatchannel.local"

# The distance players must be within to see each other's messages.
radius: 50

# Controls chat pinging
ping:
  # Should pinging be enabled?
  enable: true
  # How long should the cooldown between pings be? (in seconds)
  cooldown: 10
  # What sound should it make?
  # You can get the sound key from the /playsound command.
  sound:
    sound: entity.experience_orb.pickup
    volume: 3
    pitch: 1